//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khatra.Resources.ViewsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khatra.Resources.ViewsResources.global", typeof(global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi my name is farouk abdelhamid iam the owner of this site you can contact with me on social media any time.
        /// </summary>
        public static string AboutFounder1 {
            get {
                return ResourceManager.GetString("AboutFounder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iam web developer i have many sites i was created before if you want from me to create a one for you all you need is juast contact with me on my social media accounts.
        /// </summary>
        public static string AboutFounder2 {
            get {
                return ResourceManager.GetString("AboutFounder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can see my latest Projects on my portfolio.
        /// </summary>
        public static string AboutFounder3 {
            get {
                return ResourceManager.GetString("AboutFounder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome on my account on khatra site, this text can changed any time if account awner do it..
        /// </summary>
        public static string AboutMeDefaultContent {
            get {
                return ResourceManager.GetString("AboutMeDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this words going to shown side your photo in your account.
        /// </summary>
        public static string aboutMeDescription {
            get {
                return ResourceManager.GetString("aboutMeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is a big bolg, we try from it to push up knowledge level to arabian world on genral and for youth Especially, because they are future Builders.
        /// </summary>
        public static string AboutSite1 {
            get {
                return ResourceManager.GetString("AboutSite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and with care from us to all pepole to cover all fields we employ many pepole from articles publishers every one from them specialized in his field ,and this because we are care and we dont want from Khatra To be Source to fuck information and bad source,khatra going to be the big and trusted source in all fildes.
        /// </summary>
        public static string AboutSite2 {
            get {
                return ResourceManager.GetString("AboutSite2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the author.
        /// </summary>
        public static string AboutTheAuthor {
            get {
                return ResourceManager.GetString("AboutTheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoount Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasr City / Cairo, Egypt.
        /// </summary>
        public static string AddressContent {
            get {
                return ResourceManager.GetString("AddressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Admins.
        /// </summary>
        public static string AddToAdmins {
            get {
                return ResourceManager.GetString("AddToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Publisher.
        /// </summary>
        public static string AddToPublisher {
            get {
                return ResourceManager.GetString("AddToPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Menu.
        /// </summary>
        public static string AdminMenu {
            get {
                return ResourceManager.GetString("AdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All comments On all Posts.
        /// </summary>
        public static string AllCommentsOnAllPosts {
            get {
                return ResourceManager.GetString("AllCommentsOnAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Posts in Category.
        /// </summary>
        public static string AllPosts {
            get {
                return ResourceManager.GetString("AllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khatra.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Posts.
        /// </summary>
        public static string AuthorPosts {
            get {
                return ResourceManager.GetString("AuthorPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Languge as you want.
        /// </summary>
        public static string ChangeLangugeMsg {
            get {
                return ResourceManager.GetString("ChangeLangugeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal image.
        /// </summary>
        public static string ChangePersonalImage {
            get {
                return ResourceManager.GetString("ChangePersonalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ClickheretoLogin {
            get {
                return ResourceManager.GetString("ClickheretoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please confirm your account by clicking following link.
        /// </summary>
        public static string ConfirmMsg {
            get {
                return ResourceManager.GetString("ConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please confirm your email to use it wheen change password,just go to your email and press on our message we snd it and press &quot;confirm&quot;.
        /// </summary>
        public static string ConfirmWarniingMsg {
            get {
                return ResourceManager.GetString("ConfirmWarniingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact With Us.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farouk Abdelhamid.
        /// </summary>
        public static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and developed by.
        /// </summary>
        public static string developerRights {
            get {
                return ResourceManager.GetString("developerRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comment.
        /// </summary>
        public static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fix This Errors first.
        /// </summary>
        public static string ErrorsFirst {
            get {
                return ResourceManager.GetString("ErrorsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us on Social Media.
        /// </summary>
        public static string FollowHeading {
            get {
                return ResourceManager.GetString("FollowHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow khatra site on social media sites when bress the following buttons to take you to offishial site pages .
        /// </summary>
        public static string FollowParagraph {
            get {
                return ResourceManager.GetString("FollowParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string Forgotpassword {
            get {
                return ResourceManager.GetString("Forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to reset your password
        ///                Please check your email, if you dont find any messages from us so mybe you are not recorded in our database or your email are not confirmed yet;.
        /// </summary>
        public static string ForgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we send to your email an message with link.
        /// </summary>
        public static string ForgotPasswordConfirmationWarning {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you forgot your password you need olay to put your email and bress the button.
        /// </summary>
        public static string ForgotpasswordMsg {
            get {
                return ResourceManager.GetString("ForgotpasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have an account?.
        /// </summary>
        public static string haveAccount {
            get {
                return ResourceManager.GetString("haveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khawatr.
        /// </summary>
        public static string khawatr {
            get {
                return ResourceManager.GetString("khawatr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Posts.
        /// </summary>
        public static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong email or password, try again .
        /// </summary>
        public static string LoginProplemMsg {
            get {
                return ResourceManager.GetString("LoginProplemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to comment, you need to login first.
        /// </summary>
        public static string LoginToComment {
            get {
                return ResourceManager.GetString("LoginToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Was Sent Succssefully..
        /// </summary>
        public static string MsgSent {
            get {
                return ResourceManager.GetString("MsgSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Acoount.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Posts.
        /// </summary>
        public static string NewPosts {
            get {
                return ResourceManager.GetString("NewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont have any Categories yet!.
        /// </summary>
        public static string NoCategoryMsg {
            get {
                return ResourceManager.GetString("NoCategoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comments here yet, you can add one, Just Go to Any Post you like it and say your openion..
        /// </summary>
        public static string NoCommentsMsg {
            get {
                return ResourceManager.GetString("NoCommentsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont have any posts yet!.
        /// </summary>
        public static string NoPostsMsg {
            get {
                return ResourceManager.GetString("NoPostsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry we dont have any Users yet!.
        /// </summary>
        public static string NoUsersMsg {
            get {
                return ResourceManager.GetString("NoUsersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string PasswordChangedMsg {
            get {
                return ResourceManager.GetString("PasswordChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Comments.
        /// </summary>
        public static string PostedComments {
            get {
                return ResourceManager.GetString("PostedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Articles.
        /// </summary>
        public static string PostedPosts {
            get {
                return ResourceManager.GetString("PostedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNew {
            get {
                return ResourceManager.GetString("RegisterAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category.
        /// </summary>
        public static string RemoveCategory {
            get {
                return ResourceManager.GetString("RemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Admins.
        /// </summary>
        public static string RemoveFromAdmins {
            get {
                return ResourceManager.GetString("RemoveFromAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Publisher.
        /// </summary>
        public static string RemoveFromPublisher {
            get {
                return ResourceManager.GetString("RemoveFromPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to REMOVE this?.
        /// </summary>
        public static string RemoveMsg {
            get {
                return ResourceManager.GetString("RemoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice, Removed Successfully.
        /// </summary>
        public static string RemoveSuccessedMsg {
            get {
                return ResourceManager.GetString("RemoveSuccessedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are going to remove this user ,this action going to remove all posts and comments are related with this user and you cant recovery it be careful.
        /// </summary>
        public static string RemoveUserMsg {
            get {
                return ResourceManager.GetString("RemoveUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can find all .
        /// </summary>
        public static string RoleMsg {
            get {
                return ResourceManager.GetString("RoleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the Post On Social Media Accounts.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Categories.
        /// </summary>
        public static string SiteCategories {
            get {
                return ResourceManager.GetString("SiteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Language.
        /// </summary>
        public static string SiteLanguage {
            get {
                return ResourceManager.GetString("SiteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscripe.
        /// </summary>
        public static string Subscripe {
            get {
                return ResourceManager.GetString("Subscripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Confirme Email.
        /// </summary>
        public static string SuccessConfirmeEmail {
            get {
                return ResourceManager.GetString("SuccessConfirmeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email confirmed successfully.
        /// </summary>
        public static string SuccessConfirmeEmailMsg {
            get {
                return ResourceManager.GetString("SuccessConfirmeEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supscripe To Newslitter.
        /// </summary>
        public static string SupscripeToNewslitter {
            get {
                return ResourceManager.GetString("SupscripeToNewslitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Article Contain.
        /// </summary>
        public static string ThisCategoryContain {
            get {
                return ResourceManager.GetString("ThisCategoryContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top React Users.
        /// </summary>
        public static string TopReactUsers {
            get {
                return ResourceManager.GetString("TopReactUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Read Posts.
        /// </summary>
        public static string TopReadPosts {
            get {
                return ResourceManager.GetString("TopReadPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Post.
        /// </summary>
        public static string UpdatePost {
            get {
                return ResourceManager.GetString("UpdatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user does not Published any posts yet.
        /// </summary>
        public static string UserDontHavePosts {
            get {
                return ResourceManager.GetString("UserDontHavePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you shold use email adress like  &quot;Gmail, Outlooj, Yahoo, hotmail.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find What You Need here and Only.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Users.
        /// </summary>
        public static string WebSiteUsers {
            get {
                return ResourceManager.GetString("WebSiteUsers", resourceCulture);
            }
        }
    }
}
